<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Learning-Outcomes" data-toc-modified-id="Learning-Outcomes-1">Learning Outcomes</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#By-the-end-of-this-session,-you-should-be-able-to:" data-toc-modified-id="By-the-end-of-this-session,-you-should-be-able-to:-1.0.1">By the end of this session, you should be able to:</a></span></li></ul></li></ul></li><li><span><a href="#NumPy:-Numeric-Python" data-toc-modified-id="NumPy:-Numeric-Python-2">NumPy: Numeric Python</a></span></li><li><span><a href="#NumPy-Features-&amp;-Benefits" data-toc-modified-id="NumPy-Features-&amp;-Benefits-3">NumPy Features &amp; Benefits</a></span></li><li><span><a href="#NumPy's-array" data-toc-modified-id="NumPy's-array-4">NumPy's array</a></span></li><li><span><a href="#NumPy-is-elegant-🤵-and-fast-🐰!" data-toc-modified-id="NumPy-is-elegant-🤵-and-fast-🐰!-5">NumPy is elegant 🤵 and fast 🐰!</a></span></li><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-6">Creating Arrays</a></span></li><li><span><a href="#Generating-random-arrays-" data-toc-modified-id="Generating-random-arrays--7">Generating random arrays </a></span></li><li><span><a href="#Tensor-slicing" data-toc-modified-id="Tensor-slicing-8">Tensor slicing</a></span></li><li><span><a href="#Data-types" data-toc-modified-id="Data-types-9">Data types</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-10">Broadcasting</a></span></li><li><span><a href="#Broadcast-with-comparisons" data-toc-modified-id="Broadcast-with-comparisons-11">Broadcast with comparisons</a></span></li><li><span><a href="#NumPy-Array-methods" data-toc-modified-id="NumPy-Array-methods-12">NumPy Array methods</a></span></li><li><span><a href="#Student-Activity" data-toc-modified-id="Student-Activity-13">Student Activity</a></span></li><li><span><a href="#Stacking-arrays" data-toc-modified-id="Stacking-arrays-14">Stacking arrays</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-15">Summary</a></span></li><li><span><a href="#Bonus-Material" data-toc-modified-id="Bonus-Material-16">Bonus Material</a></span></li><li><span><a href="#Copies-and-views" data-toc-modified-id="Copies-and-views-17">Copies and views</a></span></li><li><span><a href="#Indexing-with-masks" data-toc-modified-id="Indexing-with-masks-18">Indexing with masks</a></span></li><li><span><a href="#Array-shape-manipulation" data-toc-modified-id="Array-shape-manipulation-19">Array shape manipulation</a></span></li><li><span><a href="#Argument-Maximums-and-Minimums" data-toc-modified-id="Argument-Maximums-and-Minimums-20">Argument Maximums and Minimums</a></span></li></ul></div>

<center><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" width="75%"/></center>

<center><img src="http://phdcomics.com/comics/archive/phd012611s.gif" width="75%"/></center>

I was once in grad school.

Some things were the same: lots of stress, no money, mean professors, and challenging learning environment
    
Other things were different: classes i didn't want to take, research, more research, and MATLAB

<center><h2>Learning Outcomes</h2></center>

#### By the end of this session, you should be able to:

- Explain in your words why Data Scientists use NumPy
- Create and manipulate NumPy arrays
- Perform common linear algebra operations on NumPy arrays


<center><h2>NumPy: Numeric Python</h2></center>

NumPy is is the fundamental package for scientific computing with Python. 

If it were not for NumPy, Python would not as popular in the data science world.


**Note**: It's pronounced **num-pie** as in I ❤️ **pie**, not **num-pee**.

<center><h2>NumPy Features & Benefits</h2></center>

NumPy has:

- A powerful N-dimensional array object

- Sophisticated and efficient functions

- Useful linear algebra and random number capabilities

- Tools for integrating C/C++ and Fortran code

[Source](https://www.numpy.org/)

<center><img src="images/python_data_landscape.png" width="100%"/></center>

[image link](https://higherlogicdownload.s3.amazonaws.com/IMWUC/UploadedImages/0d63eecd-fa76-4440-b4c0-a34a9e757e49/landscape.png)

From [Paco Nathan's blog on IBM website](https://community.ibm.com/community/user/datascience/blogs/paco-nathan/2019/03/12/a-landscape-diagram-for-python-data)

<center><h2>NumPy's array</h2></center>

Numpy's major feature is its `array` data type (technically, it's called an `ndarray`, but everyone just calls them arrays).

Numpy arrays, on the face of it, look a lot like a Python `list`:

In [23]:
reset -fs

In [24]:
! pip install numpy

In [25]:
import numpy as np

In [26]:
nums = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
nums[2]

30

In [28]:
# Zero-based indexing is like a moving wall - but not including
nums[:5]

array([10, 20, 30, 40, 50])

In [29]:
# Zero-based indexing is like a moving wall - picks up the first value but not last
nums[2:5]

array([30, 40, 50])

In [30]:
# Start, stop, step (stride)
nums[1:8:2]

array([20, 40, 60, 80])

In [31]:
# Revsere slicing with negative strides
nums[8:1:-2]

array([90, 70, 50, 30])

In [32]:
# Same idea for range slicing
list(range(100, -50, -10))

[100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0, -10, -20, -30, -40]

The porcelain looks the same, but the plumbing is very different things:

- Numpy arrays can hold one (and only one) type of data.
- Numpy arrays are efficient:
    - Very small memory footprint (noun)
    - Computational efficiency (verb)

<center><h2>NumPy is elegant 🤵 and fast 🐰!</h2></center>

In [33]:
nums = range(1_000)
%timeit -n 10 [_ ** 2 for _ in nums]

508 µs ± 92.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
a = np.arange(1000)

%timeit -n 10 a**2

11.4 µs ± 3.64 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Creating Arrays

In [35]:
# 1-D Arrays, aka  vectors
v = np.array([0, 1, 2, 3])

v
# v.<tab>
v.shape
v.ndim # not a column nor row vector, just a vector

1

In [36]:
# 2-D arrays, aka matrix

# 2 x 3 array (rows by columns)
m = np.array([[0, 1, 2], 
              [3, 4, 5]])    

m
m.shape
m.ndim

2

In [37]:
# N-dimensional array, aka tensors

# Data science is high dimensional. Matrices are important but limited use.
# You should get confortable with tensors
t = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

t
t.shape
t.ndim

3

In [38]:
# Systematic ways to generate arrays

# arange is to array as range is to generators / lists
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Evenly spaced points - notice that both ends are included in number of points
np.linspace(0, 10, 1) #(start, end, num_points)
np.linspace(0, 10, 2) #(start, end, num_points)
np.linspace(0, 10, 20) #(start, end, num_points)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [40]:
# Common arrays
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

`np.full` fills the array with constants

In [42]:
np.full((3, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

Generating random arrays 
----

In [43]:
# Samples from a uniform in [0, 1]
a = np.random.rand(4)       
a

array([0.54958226, 0.2535348 , 0.53478085, 0.34612491])

In [44]:
# Samples from a Gaussian
b = np.random.randn(3, 4)      
b

array([[ 0.36837507, -0.44827272, -0.18520819,  1.75776992],
       [ 0.73820989, -0.48110391,  1.36475028, -0.69925908],
       [-0.4931279 , -2.25587887,  0.88487058,  1.30041266]])

In [45]:
# Setting the random seed to get repeatible random numbers
np.random.seed(seed=42)        
b = np.random.randn(3, 4)      
b

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

Tensor slicing
------

Matrix Syntax: `[row_slice, column_slice]`

In [46]:
a = np.random.rand(3, 4)
a

array([[0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378, 0.51423444]])

In [47]:
a[:, :2]

array([[0.30424224, 0.52475643],
       [0.61185289, 0.13949386],
       [0.45606998, 0.78517596]])

Data types
----

Data types can have a dramatic effect on the computation time.  

Computations with reduced precision is much faster then greater precision.

Let's check out the [data types](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html).

In [48]:
# NumPy defaults to be as small as possible, thus more efficent
a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([1., 2., 3.])
print(b.dtype)

int64
float64


Broadcasting
-------

[Broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) arithmetic operations applied to an array is interpreted as being applied element-by-element, element-wise

In [49]:
a = np.arange(5)
print(a + 1)
print(a ** 2)

[1 2 3 4 5]
[ 0  1  4  9 16]


In [50]:
# Element-wise for same size vectors
a + a 

array([0, 2, 4, 6, 8])

In [51]:
# Multiplication is odd
a = np.ones((3,3))
print(a)

b = np.arange(9).reshape((3,3))
print(b)

a * b  # This isn't matrix multiplication




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [52]:
a.dot(b)  # This is matrix multiplication

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [53]:
a @ b # How the cool kids do matrix multiplication

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

Broadcast with comparisons
-----

In [54]:
a = np.arange(5)
a <= 3

array([ True,  True,  True,  True, False])

NumPy Array methods
-----

In [55]:
x = np.array([1, 2, 3, 4])
x.sum() # Returns a scalar

10

In [56]:
# Sum by rows 
x = np.array([[1,1],
              [2,2]])

x.sum(axis=0) # Returns a vector

array([3, 3])

In [57]:
# Sum by columns
x = np.array([[1,1],
              [2,2]])
x.sum(axis=1)

array([2, 4])

In [58]:
# Tensors
t = np.array([[[1,1],[1,1]], 
              [[2,2],[2,2]], 
              [[3,3], [3,3]]])
print(t.shape) 
t.sum(axis=2) # Returns a matrix, not a vector

(3, 2, 2)


array([[2, 2],
       [4, 4],
       [6, 6]])

<center><h2>Student Activity</h2></center>

Do on your own

- Create a 4x2 matrix  of ones
- Create a 24x7x365 tensor of uniform random numbers between [0, 1]


Stacking arrays
-----


In [59]:
a = np.floor(10*np.random.random((2,2)))


In [60]:
b = np.floor(10*np.random.random((2,2)))

In [61]:
np.vstack((a,b))

array([[5., 0.],
       [6., 1.],
       [0., 9.],
       [9., 8.]])

In [62]:
np.hstack((a,b))

array([[5., 0., 0., 9.],
       [6., 1., 9., 8.]])

[Source](https://docs.scipy.org/doc/numpy/user/quickstart.html)

<center><h2>Summary</h2></center>

- NumPy is one of the most common Data Science tools. Get comfortable with it.
- NumPy does most operations you want to do. Go find 'em.
- NumPy has a sprawling API. Learn it bit-by-bit.

Bonus Material
------

## Copies and views
A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory.

When modifying the view, the original array is modified as well:

In [63]:
a = np.arange(10)
print(a)    #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a[::2]
print(b)    #array([0, 2, 4, 6, 8])
b[0] = 12
print(b)    #array([12,  2,  4,  6,  8])
print(a)    # array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

#if you want to make changes in b without affecting a
a = np.arange(10)
b = a[::2].copy()  # force a copy
b[0] = 12
print(b) 
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]
[12  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


In [64]:
a = np.ones((100,100))
a += a.T
a

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]])

## Indexing with masks
Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not view.

In [65]:
np.random.seed(3)
a = np.random.random_integers(0, 20, 15)
print(a)   #array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])
print(a % 3 == 0)  #array of trues and falses

# Define a mask
mask = (a % 3 == 0)
extract_from_a = a[mask] # or,  a[a%3==0]
print(extract_from_a)           # extract a sub-array of %3 == 0 with the mask 

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]
[False  True False  True False False False  True False  True  True False
  True False False]
[ 3  0  9  6  0 12]


/Users/brian/anaconda3/envs/bootcamp/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  


In [66]:
# Indexing with a mask can be very useful to assign a new value to a sub-array:  
a[a % 3 == 0] = -1
print(a)

[10 -1  8 -1 19 10 11 -1 10 -1 -1 20 -1  7 14]


In [67]:
# Denerate numpy array with random values
nums = np.random.randint(50, size = (10,5))
nums

array([[26, 17, 26, 22,  2],
       [ 2,  1, 26,  5, 40],
       [46, 33, 29, 42, 24],
       [ 7, 43, 33, 15, 48],
       [37, 20, 30, 49, 21],
       [14, 28,  0,  0, 41],
       [18, 37,  7, 37, 46],
       [33, 49,  1, 21, 10],
       [43, 36, 35, 27, 16],
       [16, 32, 16, 18, 11]])

In [68]:
# Create boolean array -- True for indexes with values that satisfy the criteria
nums < 10

array([[False, False, False, False,  True],
       [ True,  True, False,  True, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [69]:
(nums < 10).any(axis=0)

array([ True,  True,  True,  True,  True])

Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1)

In [70]:
(nums < 10).any(axis=1)

array([ True,  True, False,  True, False,  True,  True,  True, False,
       False])

## Array shape manipulation

In [71]:
# Flattening

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
#order (0,0), (0,1), (0,2), (1,0), (1,1), (1,2)
print(a.ravel())   #array([1, 2, 3, 4, 5, 6])  ()
print(a.T)         #array([[1, 4], [2, 5], [3, 6]])
#order (0,0), (0,1), (1,0), (1,1), (2,0), (2,1)
print(a.T.ravel())  #array([1, 4, 2, 5, 3, 6])

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [72]:
# Reshape makes flattened array back into original
print(a.shape)   #(2, 3)
b = a.ravel()   
print(b)     #array([1,2,3,4,5,6])
print(b.reshape((2, 3)))   #array([[1, 2, 3], [4, 5, 6]])

(2, 3)
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [73]:
# Reshape also operates on non-flat array - same as flattening and then reshaping
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

Argument Maximums and Minimums
------

Sometimes you don't need to know the maximum (or minimum), but where the maximum occurs. This operation is called argument maximum.

In [74]:
x = np.random.randint(0, 100, size=10)
np.argmax(x, axis=0)

1

Very helpful for functions

In [75]:
x = np.linspace(-5, 4, num=250)
f = lambda x: x**4 + 2*x**3 - 12*x**2 - 2*x + 6

mn = np.min(f(x))
mn

-71.36363827536165

In [76]:
xmn = x[np.argmin(f(x))]  
xmn

-3.2650602409638556